# Generated by Django 4.2.4 on 2023-08-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=255)),
                ('all_students', models.BigIntegerField(default=0)),
                ('current_students', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.department')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('admission', 'Admission'), ('dropout', 'Dropout'), ('graduate', 'Graduate')], max_length=125)),
                ('event_date', models.DateField()),
                ('students', models.IntegerField(default=0)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.major')),
            ],
        ),
    ]
