# Generated by Django 4.2.4 on 2023-09-01 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.department')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.IntegerField(choices=[(0, 'Autumn'), (1, 'Spring'), (2, 'Summer'), (3, 'Winter')])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gender', models.BooleanField()),
                ('status', models.IntegerField(choices=[(0, 'No Admission'), (1, 'Studying'), (2, 'Temporarily Absent'), (3, 'Drop Out'), (4, 'Forced To Drop Out'), (5, 'Graduate')], default=0)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.major')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.IntegerField(choices=[(0, 'Gpa'), (1, 'S1'), (2, 'S2'), (3, 'S3'), (4, 'S4'), (5, 'S5'), (6, 'S6'), (7, 'S7'), (8, 'S8'), (9, 'S9'), (10, 'S10')], default=1)),
                ('value', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='college.student')),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField(choices=[(1, 'Admission'), (2, 'Temporarily Absent'), (3, 'Drop Out'), (4, 'Forced To Drop Out'), (5, 'Graduate')], default=1)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='college.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='college.student')),
            ],
        ),
    ]
